[ECO-365] Adds required dni field to customer form in checkout
mobbexco/opencart pull request #11
Opened 2023-06-29 17:55 UTC by mobbexLuis

2023-06-29 21:13 UTC, EMunozMobbex requested changes
Se añade el campo DNI al checkout de la tienda, pero pero no se esta mandando esa data al customer del checkout de Mobbex

2023-07-03 17:42 UTC, EMunozMobbex commented on admin/controller/extension/payment/mobbex.php
>              $dniField = [
Personalmente me resulta mejor visualmente que si el else va a usar llaves, el if también las tenga para mayor coherencia. Mas a modo de sugerencia

2023-07-03 17:42 UTC, EMunozMobbex commented on catalog/controller/extension/payment/mobbex.php
> +        if (!$result)
Que valor llega a $result en caso de que no exista la tabla? Ese valor convertido a booleano da false siempre?

2023-07-19 16:44 UTC, EMunozMobbex approved these changes

2023-09-12 15:52 UTC, jlmobbex approved these changes

2023-09-12 15:53 UTC, merged