Php plugins sdk integration
mobbexco/opencart pull request #12
Opened 2023-07-04 16:20 UTC by EMunozMobbex

2023-07-13 13:11 UTC, mobbexLuis commented on system/library/mobbex/sdk.php
> +     * @param MobbexConfig $config Mobbex Config Class
aca no sería @param object $config Mobbex Config Class?

2023-07-13 13:11 UTC, mobbexLuis commented on system/library/mobbex/config.php
> +
Quizas se podría incluir una doc que resuma la función de esta class

2023-07-17 18:28 UTC, EMunozMobbex commented on system/library/mobbex/sdk.php
> +     * @param MobbexConfig $config Mobbex Config Class
Se puede poner como object, class, o se puede especificar exactamente que clase es la que debe recibir como parametro, en este caso me decanté por esta ultima para que sea mas estricto en exactamente que clase es la que debe recibir, object es mas general podría recibir cualquier tipo de objeto.

2023-07-19 20:53 UTC, mobbexLuis approved these changes

2023-09-11 21:44 UTC, jlmobbex requested changes

2023-09-11 21:44 UTC, jlmobbex commented on catalog/controller/extension/payment/mobbex.php
> +        if (!\Mobbex\Repository::validateToken($token))
Quedó duplicada la validación del token antigua. También quedó el die con el mensaje de error

2023-09-11 21:44 UTC, jlmobbex commented on catalog/controller/extension/payment/mobbex.php
> +        error_log('post: ' . "\n" . json_encode($this->request->post, JSON_PRETTY_PRINT) . "\n", 3, 'log.log');
Acá quedó un log de las pruebas seguro

2023-09-11 21:44 UTC, jlmobbex commented on system/library/mobbex/sdk.php
> +                'sdk'      => class_exists('\Composer\InstalledVersions') ? \Composer\InstalledVersions::getVersion('mobbexco/php-plugins-sdk') : '',
Estaría bueno agregar la comprobación que se sumó en el resto de integraciones de si existe el paquete del sdk (`isInstalled`).

2023-09-12 14:30 UTC, jlmobbex requested changes

2023-09-12 14:30 UTC, jlmobbex commented on catalog/controller/extension/payment/mobbex.php
> +        if (!\Mobbex\Repository::validateToken($token) || empty($id) || empty($data) || $token != $this->helper->generateToken())
Bien, igualmente se sigue validando el token en duplicado. Fijate que ya no existe ni siquiera el helper para hacer `$this->helper->generateToken()`

2023-09-12 14:52 UTC, jlmobbex approved these changes

2023-09-12 15:00 UTC, merged