[ECO-298]Added Mobbex finance widget.
mobbexco/opencart pull request #13
Opened 2023-07-06 15:13 UTC by EMunozMobbex

2023-07-13 13:44 UTC, mobbexLuis commented on admin/language/es-es/extension/payment/mobbex.php
> +    'error_permission'  => 'Warning: You do not have permission to modify this config!',
quedo sin traducir esta línea

2023-07-19 20:58 UTC, mobbexLuis approved these changes

2023-09-13 04:29 UTC, jlmobbex requested changes

2023-09-13 04:29 UTC, jlmobbex commented on admin/controller/extension/module/mobbex_finance_widget.php
> +            $this->db->query(
No habría también que chequear si el valor ya fue agregado? Pregunto para saber, porque depende como esté configurada la tabla de opencart. Quizás para averiguarlo habría que hacer una prueba de instalar varias veces el plugin.

2023-09-13 04:29 UTC, jlmobbex commented on admin/view/template/extension/mobbex/finance_widget.twig
> +                            <select name="module_mobbex_finance_widget_active_product" id="input-status" class="form-control">
El atributo `id` debería ser distinto en cada opción para que al cliquear el label te seleccione la opción correcta (también modificar atributo `for` de cada label).

2023-09-13 04:29 UTC, jlmobbex commented on catalog/controller/extension/module/mobbex_finance_widget.php
> +    public function getPrice($route)
Acá recibís la ruta como param, pero para encontrarla hacés uso de `$this->request->get`, que ya se usa dentro de este método. Entonces, si la idea es aislar la lógica para que los datos que vienen por request tengan que venir si o si por param también habría que pasar el `product_id` (cosa que no me parece lo mejor). Para mí lo ideal sería que no reciba ningún param y que esté explicado en la doc del método que devuelve el precio dependiendo de la ruta actual.

2023-09-13 04:29 UTC, jlmobbex commented on catalog/controller/extension/module/mobbex_finance_widget.php
> +		\MobbexSdk::init($this->mobbexConfig);
En algunos lugares del archivo se usaron tabulaciones en vez de espacios para identar

2023-09-13 17:59 UTC, EMunozMobbex commented on admin/controller/extension/module/mobbex_finance_widget.php
> +            $this->db->query(
Hice pruebas reinstalando y no se duplican, tomé como referencia el paypal button que lo hacia de esta misma forma!

2023-09-14 18:29 UTC, jlmobbex approved these changes

2023-09-14 18:29 UTC, merged