[ECO-433] Fixed checkout total currency
mobbexco/opencart pull request #14
Opened 2023-07-20 13:53 UTC by EMunozMobbex

2023-07-21 13:35 UTC, mobbexLuis reviewed
En general son observaciones sobre archivos que se subieron en otras pr o se repitieron acá y una sugerencia

2023-07-21 13:35 UTC, mobbexLuis commented on admin/language/es-es/extension/payment/mobbex.php
> +    'error_permission'  => 'Warning: You do not have permission to modify this config!',
esto quedo sin traducir, pero ya lo comenté en otra pr
se subieron cambios duplicados?

2023-07-21 13:35 UTC, mobbexLuis commented on catalog/controller/extension/payment/mobbex.php
Este archivo , si bien tiene otros cambios, esta duplicado.

2023-07-21 13:35 UTC, mobbexLuis commented on catalog/controller/extension/payment/mobbex.php
> +    public function getStateCode($state)
Este método se podrá llevar a otro archivo para reducir el tamaño éste?
Me acuerdo de haber visto que en wp-travel se habia hecho de esa manera antes de integrarlo con el sdk.

2023-07-25 15:09 UTC, EMunozMobbex commented on admin/language/es-es/extension/payment/mobbex.php
> +    'error_permission'  => 'Warning: You do not have permission to modify this config!',
Ese cambio quedo en #13

2023-07-25 15:13 UTC, EMunozMobbex commented on catalog/controller/extension/payment/mobbex.php
> +    public function getStateCode($state)
El problema de este método es que esta hecho para resolver una particularidad de opencart que no se da en ninguna otra plataforma (devuelve las provincias unicamente por su nombre) no tendría sentido portearlo a las otras plataformas donde no se usa, diferente al de los country codes que se usa en varias.

2023-07-25 15:16 UTC, EMunozMobbex commented on catalog/controller/extension/payment/mobbex.php
No entendí este comentario 🤔

2023-07-25 15:58 UTC, mobbexLuis commented on catalog/controller/extension/payment/mobbex.php
> +    public function getStateCode($state)
Claro, no me referia a portearlo. Te cite el ejemplo de wp-travel porque en esa plugin se resovlio moviendo la tabla de country codes a un archivo propio (despues reemplazado por la del sdk)
Lo sugiero simplemente para reducir el tamaño de este archivo

2023-07-26 17:06 UTC, EMunozMobbex commented on catalog/controller/extension/payment/mobbex.php
> +    public function getStateCode($state)
Ahh ya entendí, es buena esa si creo que lo voy a aislar!

2023-09-13 04:35 UTC, jlmobbex requested changes

2023-09-13 04:35 UTC, jlmobbex commented on catalog/controller/extension/payment/mobbex.php
> +                round($order['total'] * $order['currency_value'], 2),
Siempre es mejor evitar redondeos a la hora de establecer montos, sobre todo si es el total de la transacción. Por otro lado, entiendo que esto funciona cuando uno tiene la currency en USD, pero, que pasa cuando está en ARS? No veo como puede ayudar en todos los casos.

2023-09-13 04:35 UTC, jlmobbex commented on catalog/controller/extension/payment/mobbex.php
> +    public function getStateCode($state)
Estos comentarios no están relacionados a la PR así que los resuelvo

2023-09-14 13:54 UTC, jlmobbex approved these changes

2023-09-14 13:58 UTC, merged