[ECO 458] Integrated php-plugins-sdk table model.
mobbexco/opencart pull request #17
Opened 2023-08-04 20:06 UTC by EMunozMobbex

## Notas
- Esta PR requiere para ser mergeada añadir el guardado de transacciones, con la tabla transactions refactorizada.
- También seria conveniente integrar en conjunto con el modelo de cache.

2023-09-14 18:51 UTC, jlmobbex requested changes

2023-09-14 18:51 UTC, jlmobbex commented on system/library/mobbex/db.php
> +    public function __construct($registry)
No es necesario definir el construct si es indéntico al parent, porque de ser así se ejecuta directamente ese.

2023-09-14 18:51 UTC, jlmobbex commented on system/library/mobbex/config.php
> +class MobbexConfig extends Model
Acá se introduce un cambio que colisiona con el aplicado en main sobre este modelo. En otra rama se integró el widget de financiación, y el construct de este modelo quedó modificado afectando también a este `extends Model`. Quizás lo ideal sería que quede el param `$registry` como está acá, y que en este construct se obtengan las configuraciones tanto del widget como del plugin principal.
Dejo el link para ver los cambios de esta rama:
https://github.com/mobbexco/opencart/pull/17/files/2c0d99e7a82b89d08cb4d4c200b06dfb3339c359..649d2ceb11e0c24b6f602f7cc43052833243b3bc

2023-09-14 18:51 UTC, jlmobbex commented on system/library/mobbex/logger.php
> +        $this->config = new MobbexConfig($registry);
Van a tener que revisarse las referencias del modelo de config cuando se decida que param usar. Si queda con `$registry` como param hay que mergear de master hacia acá para actualizar las referencias nuevas.

2023-09-14 18:51 UTC, jlmobbex commented on catalog/controller/extension/payment/mobbex.php
> +        parent::__construct(...func_get_args());
Muy bueno estoo!! Acorta muchas líneas del archivo

2023-09-14 18:51 UTC, jlmobbex commented on admin/view/template/extension/payment/mobbex_config.twig
> +        {% for alert in schema_notices.warning %}
Si no está definida esta posición no explota nada? Misma pregunta con `schema_notices.error`

2023-09-15 16:26 UTC, EMunozMobbex commented on admin/view/template/extension/payment/mobbex_config.twig
> +        {% for alert in schema_notices.warning %}
SI no esta definida no sucede nada, probado y funcionando bien 👯

2023-09-15 20:52 UTC, jlmobbex approved these changes

2023-09-15 20:53 UTC, merged