[ECO-303] Add product plans configuration
mobbexco/opencart pull request #18
Opened 2023-09-01 15:27 UTC by EMunozMobbex

2023-09-06 12:55 UTC, mobbexLuis approved these changes

2023-09-06 12:55 UTC, mobbexLuis commented on system/library/mobbex/config.php
> +        foreach (['common_plans', 'advanced_plans'] as $value) {
Podría mejorarse esta parte del código usando [extract()](https://www.php.net/extract)?

2023-09-06 15:58 UTC, EMunozMobbex commented on system/library/mobbex/config.php
> +        foreach (['common_plans', 'advanced_plans'] as $value) {
Lo que estoy usando ahi no son variables si no simplemente un array de labels  es decir value e sun string que dice "common_plans" o "advanced_plans" segun la iteración, los uso para asignarle valores dinacmicamente a las variables de arriba

2023-09-15 14:45 UTC, jlmobbex requested changes

2023-09-15 14:45 UTC, jlmobbex commented on system/library/mobbex/config.php
> +        return array_map(function($item){return $item['category_id'];}, $result->rows);
Esto se puede remplazar con `array_column($result->rows, 'category_id')`

2023-09-15 14:45 UTC, jlmobbex commented on system/library/mobbex/custom_field.php
> +        if($this->get($row_id, $object, $fieldName))
Acá estaría buenísimo aprovechar la funcionalidad de `REPLACE`, para no tener que hacer dos consultas a base de datos

2023-09-15 14:45 UTC, jlmobbex commented on system/library/mobbex/custom_field.php
> +        $this->table = DB_PREFIX . "mobbex_custom_fields";
Este table tiene utilidad? Si preferís dejar la propiedad para entender la tabla la podés definir como propiedad de la clase directamente, así tampoco sale un error por definir la prop dinámicamente. Si tomás ese camino además podés eliminar este construct

2023-09-15 14:45 UTC, jlmobbex commented on catalog/controller/extension/payment/mobbex.php
> +        $products_ids = array_map(function($item){return $item['product_id'];}, $this->cart->getProducts());
Acá también se puede utilizar la función de PHP `array_column`

2023-09-15 16:43 UTC, EMunozMobbex commented on system/library/mobbex/custom_field.php
> +        if($this->get($row_id, $object, $fieldName))
Replace solo toma en cuenta la clave primaria asi que en este caso en particular como no guardamos en base a la PK, no sirve y en lugar de actualizar siempre crea un registro nuevo igual pero con otro numero de PK

2023-09-15 17:01 UTC, EMunozMobbex commented on system/library/mobbex/custom_field.php
> +        $this->table = DB_PREFIX . "mobbex_custom_fields";
Seteo el table nada mas para que no haya tanta concatenacion de string en los query, pero tenes razon la puedo definet fuera del construct!

2023-09-15 21:06 UTC, jlmobbex approved these changes

2023-09-15 21:06 UTC, merged