Add save transaction to database eco 337
mobbexco/opencart pull request #8
Opened 2023-05-03 19:54 UTC by mobbexLuis

2023-08-17 16:42 UTC, EMunozMobbex requested changes
En resumen estaría interesante añadir la actualización del schema para que la tabla transaction separe la data en diferentes columnas como en todas las plataformas, de este modo nos permite acceder a esa información de forma mas cómoda.
Estaría bueno que el formato de la base de datos sea como el indicado en la definition de la feat del modelo de tabla del sdk, solo que con una columna "cart_id" en lugar de "order_id", asi se mantiene el standard de que data guardamos en que columnas.

2023-08-17 16:42 UTC, EMunozMobbex commented on catalog/controller/extension/payment/mobbex.php
> +        foreach ($this->cart->getProducts() as $product)
$this->cart no tiene el cart id?

2023-08-17 16:42 UTC, EMunozMobbex commented on catalog/controller/extension/payment/mobbex.php
> +        $this->helper->saveTransaction($this->db, $cartId, $data);
La data que se esta guardando aca en la db, es una data formateada, esto es incorrecto ya que queda fuera mucha de la data del webhook, en la posición $data de la deb deberia guardarse el webhook como llega, encodeado en json

2023-08-17 16:42 UTC, EMunozMobbex commented on system/library/mobbex/helper.php
> +    public function formatWebhookData($webhookData, $orderId)
Este metodo no tiene razón de existir ya que en las otras plataformas su logica esta para dejar la data en un formato que se corresponda a las columnas de la tabla transaction, sin embargo en opencart la tabla tranasaction solo contiene las columnas "cart_id" y "data".

A mi personalmente me parece que podrias añadir el resto de las columnas a la tabla y hacer el guardado de data que corresponde a cada columna, y en ese caso si tendria sentido que exista este metodo, pero recorda que en la columna "data" tiene que estar la data cruda como llega del webhook

2023-08-17 16:42 UTC, EMunozMobbex commented on system/library/mobbex/helper.php
> +            "INSERT INTO " . DB_PREFIX . "mobbex_transaction (cart_id, data) VALUES (" . (int) $cart_id . ", '" . json_encode($data) . "');"
Como dije antes aca se esta guardando la $data incompleta y formateada, tendria que guardarse en la columna data de la db, la data tal cual llega del webhook.

2023-08-17 19:24 UTC, EMunozMobbex commented on system/library/mobbex/helper.php
> +     * @param int   $order_id
Aca dice order_id en lugar de cart_id

2023-08-17 19:24 UTC, EMunozMobbex commented on system/library/mobbex/helper.php
> +     * Saves the transaction with order id and data
Aca dice order_id en lugar de cart_id

2023-08-17 19:24 UTC, EMunozMobbex commented on system/library/mobbex/helper.php
> +            "INSERT INTO " . DB_PREFIX . "mobbex_transaction (cart_id, data) VALUES (" . (int) $cart_id . ", '" . json_encode($data) . "');"
De esta forma se podria guardar solo la data de las columnas que existen, por otro lado hay que asegurarse que format data deje establecidos los tipados (ej que $data['data'] siempre sea un json)


```php
    
    /**
     * Saves the transaction with cart id and data
     * 
     * @param int   $cart_id
     * @param array $data
     * 
     */
    public function saveTransaction($db, $cart_id, $data)
    {
         $columns = $db->query("SHOW COLUMNS FROM " . . DB_PREFIX . "mobbex_transaction");
        
         $names = $values = [];
         
        foreach($columns as $column){
           $names[] => $column['Field'];
           $values[] => $data[$column['Field']];
        }

         $query = "INSERT INTO " . DB_PREFIX . "mobbex_transaction (". implode(', ', $names) .") VALUES (".implode(', ', $values) .");";

         $db->query($query);
    }


```

2023-08-22 16:25 UTC, mobbexLuis commented on catalog/controller/extension/payment/mobbex.php
> +        foreach ($this->cart->getProducts() as $product)
Volví a revisar y no tiene. Si, es rebuscada la forma de obtener el cart id porque se reescribe innecesariamente por cada producto. En otros plugins se obtiene de forma similar. Lamentablemente no hay un acceso sencillo desde el modelo de cart, no hay un método al estlilo de $this->cart->get_id o algo asi :/
Lo que si, pienso que se podría obtener desde cualquier product del cart sin iterar todos. Voy a checkear por qué hice ese foreach

2023-09-05 14:17 UTC, EMunozMobbex requested changes

2023-09-05 14:17 UTC, EMunozMobbex commented on system/library/mobbex/transaction.php
> +            $names[]  = $column['column_name'];
los $queryValues se pueden armar directamente aca:
```php
$names = $values = '';

foreach ($columns->rows as $key => $column) {
    $names .= $key == 0 ? "'{$column['column_name']}'" : ", '{$column['column_name']}'";
    $values .= $key == 0 ? "'{$data[$column['column_name']]}'" : ", '{$data[$column['column_name']}]'";
}

```

Asi te ahorrarias el implode y un foreach

2023-09-05 14:17 UTC, EMunozMobbex commented on system/library/mobbex/transaction.php
> +        $query = "INSERT INTO {$this->tableName} (" . implode(', ', $names) . ") VALUES ($queryValues);";
con el cambio que sugerí la query quedaría:
```php
$query = "INSERT INTO {$this->tableName} ($names) VALUES ($values);";
```

2023-09-05 16:47 UTC, EMunozMobbex approved these changes

2023-09-13 00:44 UTC, merged