[ECO-336] Add currency caution message
mobbexco/opencart pull request #9
Opened 2023-05-17 20:24 UTC by mobbexLuis

2023-08-17 16:44 UTC, EMunozMobbex requested changes

2023-08-17 16:44 UTC, EMunozMobbex commented on admin/language/en-gb/extension/payment/mobbex.php
> +    'mbbx_currency'    => 'Caution: remember to verify that the configured currency supported by Mobbex (ARS)',
quiza le pondria mbbx_currency_error para que se entienda mejor que información contiene.

2023-08-22 12:54 UTC, EMunozMobbex approved these changes

2023-08-23 00:36 UTC, jlmobbex requested changes

2023-08-23 00:36 UTC, jlmobbex commented on catalog/controller/extension/payment/mobbex.php
> +            error_log('The configured currency is not valid. Set as currency ARS:' . $order['currency_code']);
`error_log` dónde registra este mensaje? Creo que se puede usar la clase `Log` de Opencart para guardar este dato, ya que usandolo de esta forma es probable que el mensaje se pierda. Por otro lado, consulto: qué se le muestra al customer cuando sucede este error? Estaría bueno que diga que la moneda de pago no se encuentra soportada por el sitio.

2023-09-11 19:25 UTC, jlmobbex approved these changes

2023-09-11 19:26 UTC, merged